// <auto-generated />
using System;
using EmployeeDetails.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeDetails.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeDetails.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Department", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeptName = "HR"
                        },
                        new
                        {
                            Id = 2,
                            DeptName = "IT"
                        },
                        new
                        {
                            Id = 3,
                            DeptName = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            DeptName = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            DeptName = "Sales"
                        });
                });

            modelBuilder.Entity("EmployeeDetails.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 11, 14, 12, 14, 34, 689, DateTimeKind.Local).AddTicks(8424),
                            DepartmentId = 1,
                            EmpAddress = "123 Main St",
                            EmpName = "John Doe",
                            IsActive = true,
                            JoiningDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "1234567890",
                            Salary = 50000.00m
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 11, 14, 12, 14, 34, 692, DateTimeKind.Local).AddTicks(625),
                            DepartmentId = 2,
                            EmpAddress = "456 Elm St",
                            EmpName = "Jane Smith",
                            IsActive = true,
                            JoiningDate = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0987654321",
                            Salary = 60000.00m
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 11, 14, 12, 14, 34, 692, DateTimeKind.Local).AddTicks(646),
                            DepartmentId = 3,
                            EmpAddress = "789 Oak St",
                            EmpName = "Alice Johnson",
                            IsActive = false,
                            JoiningDate = new DateTime(2023, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "1122334455",
                            Salary = 55000.00m
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 11, 14, 12, 14, 34, 692, DateTimeKind.Local).AddTicks(650),
                            DepartmentId = 4,
                            EmpAddress = "321 Maple St",
                            EmpName = "Bob Brown",
                            IsActive = true,
                            JoiningDate = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "2233445566",
                            Salary = 45000.00m
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 11, 14, 12, 14, 34, 692, DateTimeKind.Local).AddTicks(652),
                            DepartmentId = 5,
                            EmpAddress = "654 Pine St",
                            EmpName = "Carol White",
                            IsActive = true,
                            JoiningDate = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "3344556677",
                            Salary = 70000.00m
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 11, 14, 12, 14, 34, 692, DateTimeKind.Local).AddTicks(655),
                            DepartmentId = 1,
                            EmpAddress = "987 Cedar St",
                            EmpName = "David Black",
                            IsActive = true,
                            JoiningDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "4455667788",
                            Salary = 52000.00m
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 11, 14, 12, 14, 34, 692, DateTimeKind.Local).AddTicks(658),
                            DepartmentId = 2,
                            EmpAddress = "159 Birch St",
                            EmpName = "Eve Green",
                            IsActive = false,
                            JoiningDate = new DateTime(2023, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "5566778899",
                            Salary = 48000.00m
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 11, 14, 12, 14, 34, 692, DateTimeKind.Local).AddTicks(660),
                            DepartmentId = 3,
                            EmpAddress = "753 Oak St",
                            EmpName = "Frank Blue",
                            IsActive = true,
                            JoiningDate = new DateTime(2023, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "6677889900",
                            Salary = 62000.00m
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2024, 11, 14, 12, 14, 34, 692, DateTimeKind.Local).AddTicks(663),
                            DepartmentId = 4,
                            EmpAddress = "951 Elm St",
                            EmpName = "Grace Red",
                            IsActive = true,
                            JoiningDate = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "7788990011",
                            Salary = 53000.00m
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2024, 11, 14, 12, 14, 34, 692, DateTimeKind.Local).AddTicks(665),
                            DepartmentId = 5,
                            EmpAddress = "357 Maple St",
                            EmpName = "Hank Yellow",
                            IsActive = false,
                            JoiningDate = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "8899001122",
                            Salary = 59000.00m
                        });
                });

            modelBuilder.Entity("EmployeeDetails.Models.Employee", b =>
                {
                    b.HasOne("EmployeeDetails.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmployeeDetails.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
